### ISSUE TITLE
TypeError for config setting

### ISSUE THREAD

**Issue by ruudvdboom** [MultiSafepay/craft-commerce#2]
When using a multisafepay.php config setting.
I get the following error:

`TypeError
Argument 1 passed to Craft::parseEnv() must be of the type string or null, bool given, called in /Users/XXXX/vendor/multisafepay/craft-commerce/src/services/SdkService.php on line 24`

To recreate the problem:
Create a config file like this:

```
use craft\helpers\App;

return [
    '*' => [
        'testMode' => true,
        'apiKey' => App::env('MSP_KEY')
    ],
    'production' => [
        'testMode' => false,
        'apiKey' => App::env('MSP_KEY')
    ],
];
```

Then:
1. Create a cart with a product
2. Go to a checkout flow
3. When posting gateway data to 'commerce/payments/pay' with the paymentMethod of MSP, this error occurs

When changing the testMode true and false to strings the problem is solved.

**Comment by J0risS** [comment]
Hi @ruudvdboom,

We released a new version: 1.3.1 and this version should fix your issue.

Thanks very much for reporting this issue! If you run into any more problems or have additional feedback/improvements for us, please feel free to reach out or create a new issue!
